<a href="https://colab.research.google.com/github/nishantdeswal1810/DeepLearning/blob/main/Churn_Modelling_ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

# **Data Preprocessing**

In [8]:
dataset=pd.read_csv('Churn_Modelling.csv')
dataset.sample(5)

RowNumber  CustomerId      Surname  CreditScore Geography  Gender  Age  \
5325       5326    15599126      Russell          529    France  Female   43   
2603       2604    15583049      Wallace          643   Germany  Female   34   
440         441    15782735  Chukwuemeka          626    France  Female   35   
7149       7150    15699340       Okorie          680    France    Male   37   
9281       9282    15679966        Marsh          661    France  Female   31   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
5325       0  123815.86              1          1               1   
2603       7  160426.07              1          0               1   
440        3       0.00              1          0               0   
7149       4       0.00              2          1               0   
9281       3  133964.30              1          1               1   

      EstimatedSalary  Exited  
5325         78463.99       1  
2603        188533.11       0  
440          80190.36       0  
7149         61240.87       0  
9281        166187.10       0

In [13]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [10]:
x=dataset.iloc[:,3:-1].values  # row number, customer id , surname is not useful
y=dataset.iloc[:,-1].values

In [11]:
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [12]:
y

array([1, 0, 1, ..., 1, 1, 0])

In [14]:
# label encoding the Gender column
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
x[:,2] =le.fit_transform(x[:,2])

In [15]:
x

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

In [16]:
# one hot encoding the geography column
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')
x=np.array(ct.fit_transform(x))

In [17]:
x

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [18]:
# split dataset into the Training set and test set
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [19]:
# feature scaling
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

# **Building the ANN**

In [21]:
# Initializing the ANN
ann=tf.keras.models.Sequential()

In [23]:
# adding the input layer and the first hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [24]:
# adding the second hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [25]:
# adding the output layer

ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))
# if the problem was non-binary classification, we would have used softmax activation function

# Training the ANN

In [27]:
# compiling the ANN
ann.compile(optimizer='adam', loss='binary_crossentropy' , metrics='accuracy')
# if the problem was non-binary classification, we would have used categorical_crossentropy

In [28]:
# Training the ANN on the Training set
ann.fit(x_train,y_train, batch_size=32, epochs=100)

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.5768 - accuracy: 0.7312
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4754 - accuracy: 0.7954
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4511 - accuracy: 0.7970
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4366 - accuracy: 0.7996
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4279 - accuracy: 0.8039
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4223 - accuracy: 0.8073
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4179 - accuracy: 0.8091
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4146 - accuracy: 0.8109
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4103 - accuracy: 0.8133
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4049 - accura

# Making the prediction and evaluating the model

In [36]:
# input must be a 2D array
# france's one hot endoiding value was 1,0,0
# male's label encoiding value was 1
# don't forget to apply scaling
print(ann.predict(sc.transform([[1, 0, 0 , 600 , 1 ,40 , 3, 60000 ,2, 1, 1, 50000]]))>0.5)

1/1 [==============================] - 0s 24ms/step
[[False]]


## predicting the test results

In [37]:
y_pred=ann.predict(x_test)
y_pred=(y_pred>0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 946us/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


## Making the Confusion matrix

In [38]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm=confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[1514   81]
 [ 194  211]]


0.8625